budget_project/budget_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('accounts/login/', views.login_view, name="login"),

]

budget_project/budget_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("budget_app.urls")),


]

budget_project/budget_app/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError


def get_current_date():
    return timezone.now().date()


COLOR_CHOICES = [
    ('#FF5733', 'Red'),
    ('#33FF57', 'Green'),
    ('#3366FF', 'Blue'),
    ('#FFFF33', 'Yellow'),
    ('#FF33FF', 'Purple'),
    ('#FFA07A', 'Light Salmon'),
    ('#32CD32', 'Lime Green'),
    ('#1E90FF', 'Dodger Blue'),
    ('#FFD700', 'Gold'),
    ('#9932CC', 'Dark Orchid'),
    ('#20B2AA', 'Light Sea Green'),
    ('#FF69B4', 'Hot Pink'),
    ('#7B68EE', 'Medium Slate Blue'),
    ('#00FF7F', 'Spring Green'),
    ('#FF4500', 'Orange Red'),
    ('#8A2BE2', 'Blue Violet'),
    ('#ADFF2F', 'Green Yellow'),
    ('#00CED1', 'Dark Turquoise'),
    ('#FF6347', 'Tomato'),
]

ICON_CHOICES = [
    ('🏠', 'Housing'),           # Home
    ('🚗', 'Transportation'),    # Car
    ('🍔', 'Food'),              # Food
    ('💡', 'Utilities'),         # Utilities
    ('🏥', 'Healthcare'),        # Healthcare
    ('💳', 'Debt Payments'),     # Debt Payments
    ('🎬', 'Entertainment'),     # Entertainment
    ('🎓', 'Education'),         # Education
    ('💇', 'Personal Care'),     # Personal Care
    ('👚', 'Clothing'),          # Clothing
    ('💰', 'Savings'),           # Savings
    ('🎁', 'Gifts'),             # Gifts
    ('💸', 'Taxes'),             # Taxes
    ('🧸', 'Childcare'),         # Childcare
    ('✈️', 'Travel'),           # Travel
    ('💼', 'Employment Income'), # Employment Income
    ('💼', 'Self-Employment Income'),  # Self-Employment Income
    ('💰', 'Investment Income'),      # Investment Income
    ('🏢', 'Rental Income'),          # Rental Income
    ('🔀', 'Other Sources of Income'), # Other Sources of Income
]

class Circle(models.Model):
    name = models.CharField(max_length=100)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name='admin_circles')
    members = models.ManyToManyField(User)
    icon = models.CharField(max_length=2, default='🏠')  # Default emoji for 'Housing'
    color = models.CharField(max_length=7, choices=COLOR_CHOICES, default=1)  # Use a CharField for color with a max length of 7

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)
    circle = models.ForeignKey(Circle, on_delete=models.CASCADE, default=1)
    icon = models.CharField(max_length=2, default='🏠')
    color = models.CharField(max_length=7, choices=COLOR_CHOICES, default=1)

    def __str__(self):
        return f"{self.name}"  # Display the circle name and category name
        # return f"{self.circle.name} - {self.name}"  # Display the circle name and category name


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Transaction(models.Model):  
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    TRANSACTION_TYPE_CHOICES = [  
        ('expense', 'Expense'),
        ('income', 'Income'),
    ]
    type = models.CharField(max_length=10, choices=TRANSACTION_TYPE_CHOICES, default='expense')  
    date_of_transaction = models.DateField(default=get_current_date)
    date_of_update = models.DateField(default=get_current_date)
    amount = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(99999999.99)  
        ]
    )
    description = models.CharField(max_length=100, blank=True, null=True)
    comment = models.CharField(max_length=100, blank=True, null=True)
    recurrence = models.BooleanField(default=False)
    RECURRENCE_UNITS_CHOICES = [
        ('days', 'Days'),
        ('weeks', 'Weeks'),
        ('months', 'Months'),
        ('years', 'Years'),
    ]
    units_of_recurrence = models.CharField(
        max_length=7,
        choices=RECURRENCE_UNITS_CHOICES,
        blank=True,
        null=True,
        default='months'  
    )
    interval_of_recurrence = models.PositiveIntegerField(
        blank=True,
        null=True,
        validators=[MinValueValidator(1)],
        default=1
    )
    recurrence_end_date = models.DateField(null=True, blank=True)

    def validate_recurrence_end_date(self):
        if self.recurrence_end_date and self.recurrence_end_date <= self.date_of_transaction:
            raise ValidationError("Recurrence end date must be after the date of transaction.")
    

    def __str__(self):
        return f"{self.date_of_transaction} - {self.category} - {self.description} - {self.author.username} - {self.amount}"

    def clean(self):
        self.validate_recurrence_end_date()

class Goal(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(99999999.99)
        ]
    )
    PERIOD_TYPE_CHOICES = [
        ('rolling', 'Rolling'),
        ('fixed', 'Fixed'),
    ]
    period_type = models.CharField(max_length=10, choices=PERIOD_TYPE_CHOICES)
    period = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.category} - {self.sub_category} - {self.amount}"


def create_personal_circle(user):
    # Create a "Personal" circle for the user
    personal_circle = Circle.objects.create(name="Personal", admin=user)
    
    # Create a default category linked to the "Personal" circle
    Category.objects.create(name="Default", circle=personal_circle)

# Override the User model to create a Personal circle and set it as the default category
User.add_to_class('personal_circle', models.OneToOneField(
    Circle, null=True, on_delete=models.SET_NULL, related_name='personal_owner'
))

def user_post_save(sender, instance, **kwargs):
    if not hasattr(instance, 'personal_circle'):
        create_personal_circle(instance)

models.signals.post_save.connect(user_post_save, sender=User)

budget_project/budget_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.shortcuts import render, redirect, get_object_or_404
from django import forms
from .models import Category, Transaction, User, Circle, Goal, SubCategory
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.utils import timezone 
from django.db.models import Count
from .reset_demo_user import reset_demo_user_data

class NewTransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['category', 'sub_category', 'type', 'date_of_transaction', 'description', 'comment', 'recurrence', 'units_of_recurrence', 'interval_of_recurrence', 'recurrence_end_date', 'amount']

    def __init__(self, user, *args, **kwargs):
        super(NewTransactionForm, self).__init__(*args, **kwargs)
        # Limit the category choices to those of the user's circles
        self.fields['category'].queryset = Category.objects.filter(circle__members=user)

        # Customize the display of the Category field choices
        self.fields['category'].label_from_instance = lambda obj: f"{obj.circle.name} - {obj.name}"


class NewCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'circle', 'icon', 'color']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Get the 'user' argument from kwargs
        super(NewCategoryForm, self).__init__(*args, **kwargs)
        
        if user:
            # Limit the circle choices to those that the user is a member of
            self.fields['circle'].queryset = Circle.objects.filter(members=user)

@login_required
def index(request):
    if request.method == "POST":
        transaction_form = NewTransactionForm(request.user, request.POST)
        category_form = NewCategoryForm(user=request.user, data=request.POST)  # Pass user=request.user

        if transaction_form.is_valid():
            new_transaction = transaction_form.save(commit=False)
            new_transaction.author = request.user
            new_transaction.save()
            return redirect("index")
    
        elif category_form.is_valid():
            new_category = category_form.save(commit=False)
            new_category.author = request.user
            new_category.save()
            return redirect("index")

    else:
        transaction_form = NewTransactionForm(request.user)
        category_form = NewCategoryForm(user=request.user)  # Pass user=request.user

    transactions = Transaction.objects.filter(author=request.user).order_by('-date_of_update')

    return render(request, "budget_app/index.html", {
        "transactions": transactions,
        "transaction_form": transaction_form,
        "category_form": category_form,
    })

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            demo_username = "user-demo"
            if username == demo_username:
                reset_demo_user_data(user)
                login(request, user)
                return redirect("index")
            else:
                login(request, user)
                return redirect("index")
        else:
            return render(request, "budget_app/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        if request.user.is_authenticated:
            return redirect("index")
        else:
            return render(request, "budget_app/login.html")

def logout_view(request):
    logout(request)
    return redirect("login")

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "budget_app/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
            # Create two circles for the "demo-user"
            personal_circle = Circle.objects.create(
                name="Personal",
                admin=user,
                color='#FF5733',  # Specify the color
                icon='🏠',  # Specify the icon
                )
            personal_circle.members.add(user)
            
            Category.objects.create(
            name='Miscellaneous',
            circle=personal_circle,
            icon='🍬',
            color='#FF33FF',
            )

        except IntegrityError:
            return render(request, "budget_app/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return redirect("index")
    else:
        if request.user.is_authenticated:
            return redirect("index")
        else:
            return render(request, "budget_app/register.html")

budget_project/budget_app/templates/budget_app/index.html
{% extends "budget_app/layout.html" %}
{% load static %}

{% block style %}
{% endblock %}

{% block script %}
    <script src="{% static 'budget_app/script.js' %}"></script>
    
{% endblock %}

{% block body %}

<h1 class="text-3xl font-semibold mb-4">Budget Transactions</h1>

<div class="mb-8">
    <h1>Add Transaction</h1>
    <form method="post">
        {% csrf_token %}
        {{ transaction_form.as_p }}
        <button type="submit">Save Transaction</button>
    </form>
</div>

<!-- <div class="mb-8">
    <h2 class="text-xl font-semibold mb-2">Create New Transaction:</h2>
    <form method="post">
        {% csrf_token %}
        {{ transaction_form.non_field_errors }}
        <div class="mb-4">
            {{ transaction_form.amount.label_tag }} {{ transaction_form.amount }}
        </div>
        <div class="mb-4">
            {{ transaction_form.date.label_tag }} {{ transaction_form.date }}
        </div>
         <div class="mb-4">
            {{ transaction_form.category.label_tag }}
            {{ transaction_form.category }}
                <button id="openModalBtn" type="button" class="ml-2 bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-2 rounded">
                    <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
                    </svg>
                </button>  
        </div>
        <div class="mb-4">
            {{ transaction_form.type.label_tag }} 

            <div id="id_type">
                <div>
                <label for="id_type_0"><input type="radio" name="type" value="expense" required="" id="id_type_0" checked="">Expense</label>
                </div>
                <div>
                <label for="id_type_1"><input type="radio" name="type" value="income" required="" id="id_type_1">Income</label>
                </div>
            </div>
        </div>
        <div class="mb-4">
            {{ transaction_form.description.label_tag }} {{ transaction_form.description }}
        </div>
        <div class="mb-4">
            {{ transaction_form.comment.label_tag }} {{ transaction_form.comment }}
        </div>
        <button type="submit" class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded">
            Add Transaction
        </button>
    </form>
</div> -->

<div class="mb-8">
    <h2 class="text-xl font-semibold mb-2">Last Entered Transactions:</h2>
    <ul>
        {% for transaction in transactions %}
            <li class="mb-2"> ({{ transaction.date_of_transaction }}) {{ transaction.category }}   - {{ transaction.description }} {{ transaction.amount }}</li>
        {% endfor %}
    </ul>
</div>
Add Category:

<button id="openModalBtn" type="button" class="ml-2 bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-2 rounded">
    <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
    </svg>
</button> 

<br>
<div id="myModal" class="modal hidden fixed inset-0 z-50 overflow-auto bg-black bg-opacity-40 flex justify-center items-center">
    <div class="modal-content bg-white p-4 rounded shadow-lg">
        <div class="flex justify-end">
            <button id="closeModalBtn" class="text-gray-700 hover:text-gray-900">
                <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                </svg>
            </button>
        </div>
        <h1 class="text-2xl font-semibold mb-4">Create New Category:</h1>
        <form method="post">
            {% csrf_token %}
            {{ category_form.as_p }}
            <button type="submit" class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded">
                Add Category
            </button>
        </form>
    </div>
</div>

{% endblock %}

budget_project/budget_app/templates/budget_app/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block style %}
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Budget</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'budget_app/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    


</head>
    <body>
            {% block body %}
            {% endblock %}
            {% block script %}
            {% endblock %}
            <br>
            <a href="{% url 'logout' %}" class="text-blue-500 hover:underline">Logout</a>

    </body>
</html>

budget_project/budget_app/templates/budget_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>

    <div class="login-register">
        <h2>Login</h2>
    
        {% if message %}
            <div>{{ message }}</div>
        {% endif %}
    
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="button-8" role="button" type="submit" value="Login"></input>
        </form>
        
    
        <p> Don't have an account? <a href="{% url 'register' %}">Register here.</a>
        </p>
    </div>
    
</body>
</html>

budget_project/budget_app/templates/budget_app/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <div class="login-register">
        <h2>Register</h2>
    
        {% if message %}
            <div>{{ message }}</div>
        {% endif %}
    
        <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <input class="button-8" role="button" type="submit" value="Register"></input>
        </form>
    
        Already have an account? <a href="{%  url 'index' %}">Log In here.</a>
    </div>
    
</body>
</html>